### ISSUE TITLE
semantic should be 2.2.13 and rtl maybe??

### ISSUE THREAD

**Issue by shevetonline** [awurth/slim-base#4]
can you add an option for rtl = both in the config
i did it manually copied from another install 
but not sure if everything would work
 didnt get that far yet to test

**Comment by awurth** [comment]
Bower will automatically install the last version of Semantic when you run `bower install`.

I don't think you can install Semantic UI with RTL with Bower. You have to install it with npm and set the `rtl` option to `true` in `semantic.json`:

``` bash
$ npm install semantic-ui --save

# Then set "rtl" option to "true" in semantic.json

$ cd semantic
$ gulp build
```

**Comment by awurth** [comment]
Bower will automatically install the last version of Semantic when you run `bower install`.

About RTL:
Apparently, if you downloaded Semantic UI with Bower, you have to run `npm install` in the `semantic` folder to install the dependencies for gulp tasks. Then you have to copy the `semantic.json.example` to `semantic.json` and set the "rtl" option to "true". Then copy `src/theme.config.example` to `src/theme.config`. Finally, run `gulp build` to generate RTL CSS files.

A better solution would be to install Semantic UI with npm:
``` bash
$ npm install semantic-ui --save

# Then set "rtl" option to "true" in semantic.json

$ cd semantic
$ gulp build
```

**Comment by shevetonline** [comment]
saw you removed bower
better since they no longer recommend using it
it has been replaced by yarn or npm to most packages
great
closed !!

**Comment by shevetonline** [comment]
rtl has 3 states
true fals and both
to use both change
"rtl": "both",
its diffrent needs extra quotes
