### ISSUE TITLE
utf8mb4 https://laravel-news.com/laravel-5-4-key-too-long-error

### ISSUE THREAD

**Issue by shevetonline** [awurth/slim-base#5]
change of charset  utf8mb4
and
coalltion to utf8mb4_unicode_ui
the new standard for database to include emoji 

https://laravel-news.com/laravel-5-4-key-too-long-error

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes 

solution 
public function boot()
{
    Schema::defaultStringLength(191);
}

**Comment by awurth** [comment]
Thanks, I fixed this in v3.0.6.
